// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_WEB']!,
    appId: '1:922033622398:web:b60c66cf9f5710955b772f',
    messagingSenderId: '922033622398',
    projectId: 'v2-cap-arc-d2d54',
    authDomain: 'v2-cap-arc-d2d54.firebaseapp.com',
    storageBucket: 'v2-cap-arc-d2d54.appspot.com',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_ANDROID']!,
    appId: '1:922033622398:android:90d9a16ccf720cd85b772f',
    messagingSenderId: '922033622398',
    projectId: 'v2-cap-arc-d2d54',
    storageBucket: 'v2-cap-arc-d2d54.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_IOS']!,
    appId: '1:922033622398:ios:8a0f89348ab0a4c85b772f',
    messagingSenderId: '922033622398',
    projectId: 'v2-cap-arc-d2d54',
    storageBucket: 'v2-cap-arc-d2d54.appspot.com',
    iosBundleId: 'com.example.caparc',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_API_KEY_MACOS']!,
    appId: '1:922033622398:ios:52c6ee4a15ffb6ff5b772f',
    messagingSenderId: '922033622398',
    projectId: 'v2-cap-arc-d2d54',
    storageBucket: 'v2-cap-arc-d2d54.appspot.com',
    iosBundleId: 'com.example.caparc.RunnerTests',
  );
}
